import {detectProjectType,extractPrintableStrings,analyzeTextForPlugins,mergePluginFindings,matchInventory,makeCsvReport,makeTextReport,parseInventoryText,makeRecoveryChecklist} from './parser-core.js';

const $=s=>document.querySelector(s); const state={files:[],findings:[],inventory:[]};
const fmt=new TextDecoder('utf-8',{fatal:false});

function humanBytes(n){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`}
function safeText(bytes){return fmt.decode(bytes)}
async function gunzip(bytes){const ds=new DecompressionStream('gzip');return new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(ds)).arrayBuffer())}
function u16(v,o){return v.getUint16(o,true)} function u32(v,o){return v.getUint32(o,true)}
async function unzipTextEntries(bytes){const out=[];const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--){if(u32(v,i)===0x06054b50){eocd=i;break}}if(eocd<0)return out;const count=u16(v,eocd+10),cdOffset=u32(v,eocd+16);let p=cdOffset;for(let i=0;i<count&&p+46<=bytes.length;i++){if(u32(v,p)!==0x02014b50)break;const method=u16(v,p+10),csize=u32(v,p+20),usize=u32(v,p+24),nlen=u16(v,p+28),xlen=u16(v,p+30),clen=u16(v,p+32),local=u32(v,p+42);const name=safeText(bytes.slice(p+46,p+46+nlen));p+=46+nlen+xlen+clen;if(csize>30_000_000||usize>60_000_000)continue;if(!/\.(xml|json|txt|plist|rpp|cfg|ini|vstpreset|settings?)$|metadata|project|song|plugin/i.test(name))continue;try{const ln=u16(v,local+26),lx=u16(v,local+28),start=local+30+ln+lx;let data=bytes.slice(start,start+csize);if(method===8){const ds=new DecompressionStream('deflate-raw');data=new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer())}else if(method!==0)continue;out.push({name,text:safeText(data).slice(0,8_000_000)})}catch{}}
return out}

async function analyzeFile(file){const max=80_000_000;let bytes=new Uint8Array(await file.slice(0,max).arrayBuffer());const type=detectProjectType(file.name,bytes);const rec={name:file.name,size:file.size,daw:type.daw,container:type.container,confidence:type.confidence,notes:[],members:0,truncated:file.size>max};let chunks=[];if(rec.truncated)rec.notes.push('Scan capped at first 80 MB for browser safety.');try{if(file.name.toLowerCase().endsWith('.als')||(bytes[0]===0x1f&&bytes[1]===0x8b)){bytes=await gunzip(bytes);chunks.push({source:file.name,text:safeText(bytes),confidence:'high'});rec.notes.push('gzip payload decompressed locally.')}else if((bytes[0]===0x50&&bytes[1]===0x4b)||/\.(song|zip|logicx|band)$/i.test(file.name)){const entries=$('#deepScan').checked?await unzipTextEntries(bytes):[];rec.members=entries.length;for(const e of entries)chunks.push({source:`${file.name} › ${e.name}`,text:e.text,confidence:'high'});rec.notes.push($('#deepScan').checked?(entries.length?`${entries.length} textual archive members inspected.`:'Archive/container detected; no readable textual members recovered.'):'Deep archive scan disabled; container scanned using printable strings only.');if(!entries.length)chunks.push({source:file.name,text:extractPrintableStrings(bytes,+$('#minString').value).join('\n'),confidence:'low'})}else if(/\.(rpp|rpp-bak|xml|json|txt)$/i.test(file.name)){chunks.push({source:file.name,text:safeText(bytes),confidence:'high'})}else{chunks.push({source:file.name,text:extractPrintableStrings(bytes,+$('#minString').value).join('\n'),confidence:'low'});rec.notes.push('Proprietary/unknown binary scanned using printable-string evidence.')}}catch(err){rec.notes.push(`Decoder fallback used: ${err.message}`);chunks.push({source:file.name,text:extractPrintableStrings(bytes,+$('#minString').value).join('\n'),confidence:'low'})}
let findings=[];for(const c of chunks)findings.push(...analyzeTextForPlugins(c.text,{source:c.source,daw:type.daw,confidence:c.confidence}));return {rec,findings}}

async function handleFiles(files){if(!files.length)return;$('#workspace').classList.remove('hidden');$('#riskBanner').textContent='Scanning locally…';for(const file of files){const {rec,findings}=await analyzeFile(file);state.files.push(rec);state.findings.push(...findings)}state.findings=matchInventory(mergePluginFindings(state.findings),state.inventory);render()}
function render(){const refs=state.findings.reduce((n,f)=>n+f.occurrences,0),daws=new Set(state.files.map(f=>f.daw).filter(x=>x!=='Unknown')).size,high=state.findings.filter(f=>f.confidence==='high').length,matches=state.findings.filter(f=>f.installedStatus==='matched').length,missing=state.findings.filter(f=>f.installedStatus==='not found').length;$('#summary').innerHTML=[['FILES',state.files.length],['DAWS',daws],['REFERENCES',refs],['UNIQUE PLUGINS',state.findings.length],['HIGH CONF.',high],['MATCHED',matches]].map(([l,v])=>`<div class="stat"><strong>${v}</strong><span>${l}</span></div>`).join('');$('#riskBanner').textContent=`${state.findings.length?'Analysis complete.':'No plugin references were confidently recovered.'} ${state.files.some(f=>/binary|unknown/i.test(f.container))?'One or more files use proprietary/opaque binary storage, so some results are heuristic.':''} ${state.inventory.length?`${missing} referenced plugin${missing===1?'':'s'} did not match the supplied inventory.`:'Load a plugin inventory if you want installed/missing cross-checking.'}`;renderFiles();populateFormats();renderPlugins()}
function populateFormats(){const sel=$('#formatFilter'),cur=sel.value;sel.innerHTML='<option value="">All formats</option>'+[...new Set(state.findings.map(f=>f.format))].sort().map(x=>`<option>${esc(x)}</option>`).join('');sel.value=cur}
function renderFiles(){$('#fileList').innerHTML=state.files.map(f=>`<div class="file-card"><strong>${esc(f.name)}</strong><span>${esc(f.daw)} · ${esc(f.container)} · ${humanBytes(f.size)} · ${esc(f.confidence)} confidence${f.members?` · ${f.members} members`:''}</span>${f.notes.map(n=>`<p>${esc(n)}</p>`).join('')}</div>`).join('')||'<p>No files scanned.</p>'}
function renderPlugins(){const q=$('#search').value.toLowerCase(),ff=$('#formatFilter').value,cf=$('#confidenceFilter').value,inf=$('#installedFilter').value;const showLow=$('#lowConfidence').checked;const list=state.findings.filter(f=>(showLow||f.confidence!=='low')&&(!q||`${f.name} ${f.vendor} ${f.category}`.toLowerCase().includes(q))&&(!ff||f.format===ff)&&(!cf||f.confidence===cf)&&(!inf||f.installedStatus===inf));$('#pluginList').innerHTML=list.map(f=>`<article class="plugin"><div class="plugin-main"><div class="plugin-name"><strong>${esc(f.name)}</strong><span>${esc(f.vendor)}</span></div><div class="plugin-cell">${esc(f.category)}</div><div class="plugin-cell">${esc(f.format)}</div><div><span class="pill ${esc(f.confidence)}">${esc(f.confidence)}</span></div><div><span class="pill ${esc(f.installedStatus.replaceAll(' ','-'))}">${esc(f.installedStatus)}</span></div></div><details><summary>Explain & show evidence</summary><p>${esc(f.explanation)}</p><p><b>Occurrences/evidence:</b> ${f.occurrences} &nbsp; <b>Sources:</b> ${esc(f.sources.join(', '))}${f.inventoryMatch?`<br><b>Inventory match:</b> ${esc(f.inventoryMatch)}`:''}</p>${$('#keepEvidence').checked?`<pre class="evidence">${esc(f.evidence.join('\n\n'))}</pre>`:''}</details></article>`).join('')||'<p class="privacy-note">No plugins match the current filters.</p>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function reset(){state.files=[];state.findings=[];state.inventory=[];$('#workspace').classList.add('hidden');$('#inventoryStatus').textContent='No inventory loaded';$('#fileInput').value='';$('#inventoryFolder').value='';$('#inventoryFile').value=''}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function summaryText(){return makeTextReport(state.files,state.findings)}

$('#browseBtn').onclick=e=>{e.stopPropagation();$('#fileInput').click()};$('#dropZone').onclick=()=>$('#fileInput').click();$('#dropZone').onkeydown=e=>{if(e.key==='Enter'||e.key===' ')$('#fileInput').click()};$('#fileInput').onchange=e=>handleFiles([...e.target.files]);['dragenter','dragover'].forEach(ev=>$('#dropZone').addEventListener(ev,e=>{e.preventDefault();$('#dropZone').classList.add('drag')}));['dragleave','drop'].forEach(ev=>$('#dropZone').addEventListener(ev,e=>{e.preventDefault();$('#dropZone').classList.remove('drag')}));$('#dropZone').addEventListener('drop',e=>handleFiles([...e.dataTransfer.files]));
$('#inventoryFolder').onchange=e=>{state.inventory=[...e.target.files].map(f=>f.webkitRelativePath||f.name).filter(p=>/\.(vst3|vst|component|aaxplugin|clap|dll)$/i.test(p));$('#inventoryStatus').textContent=`${state.inventory.length} plugin files indexed locally`;state.findings=matchInventory(state.findings,state.inventory);render()};
$('#inventoryFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;const t=await f.text();state.inventory=parseInventoryText(t,f.name);$('#inventoryStatus').textContent=`${state.inventory.length} inventory entries loaded locally`;state.findings=matchInventory(state.findings,state.inventory);render()};
['search','formatFilter','confidenceFilter','installedFilter','keepEvidence','lowConfidence'].forEach(id=>$('#'+id).addEventListener('input',renderPlugins));$('#resetBtn').onclick=reset;$('#copyBtn').onclick=()=>navigator.clipboard.writeText(summaryText());document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>{const t=b.dataset.export;if(t==='json')download('pluginchek-report.json',JSON.stringify({generated:new Date().toISOString(),files:state.files,plugins:state.findings},null,2),'application/json');if(t==='csv')download('pluginchek-plugins.csv',makeCsvReport(state.findings),'text/csv');if(t==='txt')download('pluginchek-report.txt',summaryText());if(t==='recovery')download('pluginchek-recovery-checklist.txt',makeRecoveryChecklist(state.findings))});
