// Browser end-to-end check. Usage: node scripts/e2e.mjs   (needs Playwright + Chromium; set PLAYWRIGHT_MODULE to its index.mjs)
import http from 'node:http';
import { readFileSync, writeFileSync, mkdtempSync, existsSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
import { tmpdir } from 'node:os';
import { join, extname } from 'node:path';
import assert from 'node:assert/strict';

const pwPath = process.env.PLAYWRIGHT_MODULE || '/opt/node22/lib/node_modules/playwright/index.mjs';
const { chromium } = await import(pwPath);
const types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json' };
const srv = http.createServer((q, r) => { const p = new URL(q.url, 'http://x').pathname; const f = join(process.cwd(), p === '/' ? 'index.html' : p.slice(1)); if (p.includes('..') || !existsSync(f)) { r.writeHead(404).end(); return; } r.writeHead(200, { 'content-type': types[extname(f)] || 'application/octet-stream' }).end(readFileSync(f)); }).listen(0);
const url = `http://localhost:${srv.address().port}/`;
const dir = mkdtempSync(join(tmpdir(), 'pc-e2e-'));
writeFileSync(join(dir, 'basic.als'), gzipSync(readFileSync('tests/fixtures/ableton/basic.als.xml')));
writeFileSync(join(dir, 'basic.rpp'), readFileSync('tests/fixtures/reaper/basic.rpp'));
writeFileSync(join(dir, 'evil.rpp'), '<REAPER_PROJECT 0.1\n  <TRACK\n    <FXCHAIN\n      <VST "VST3: <img src=x onerror=window.__pwned=1> (<b>Evil</b>)" evil.vst3 0 "" 1{AAAABBBBCCCCDDDDEEEEFFFF00001111}\n      >\n    >\n  >\n');
writeFileSync(join(dir, 'inv.json'), JSON.stringify(['FabFilter Pro-Q 3.vst3', 'Serum_x64.dll']));

const browser = await chromium.launch({ executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium' });
const page = await browser.newPage();
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => m.type() === 'error' && !/status of 404/.test(m.text()) && errors.push(m.text()));
page.on('response', r => r.status() === 404 && !/favicon\.ico$/.test(r.url()) && errors.push(`404 ${r.url()}`));
await page.goto(url);
await page.setInputFiles('#fileInput', [join(dir, 'basic.als'), join(dir, 'basic.rpp'), join(dir, 'evil.rpp')]);
await page.waitForSelector('#pluginList .plugin');
const verdict = await page.innerText('#verdict');
assert.match(verdict, /Found \d+ plugins/, verdict);
assert.ok(!/missing/i.test(verdict.replace('what is missing', '')), 'no "missing" claim without inventory');
assert.equal(await page.evaluate(() => window.__pwned), undefined, 'XSS payload must stay inert');
assert.equal(await page.locator('#pluginList img').count(), 0);
await page.setInputFiles('#inventoryFile', join(dir, 'inv.json'));
await page.waitForFunction(() => document.querySelector('#verdict').textContent.includes('installed'));
const v2 = await page.innerText('#verdict');
assert.match(v2, /missing/i);
assert.ok(await page.locator('#panel-media').isVisible(), 'media panel visible');
assert.ok(await page.locator('#panel-compat').isVisible(), 'compat panel visible');
assert.ok(await page.locator('#panel-stats').isVisible(), 'stats panel visible with 3 files');
await page.check('#problemsOnly');
const n = await page.locator('#pluginList .plugin').count();
assert.ok(n >= 1);
const [dl] = await Promise.all([page.waitForEvent('download'), page.click('[data-export="json"]')]);
const rep = JSON.parse(readFileSync(await dl.path(), 'utf8'));
assert.equal(rep.schema, 2); assert.ok(rep.plugins.length >= 4);
await page.click('#themeBtn');
assert.ok(await page.evaluate(() => document.documentElement.dataset.theme === 'dark'));
await page.click('#resetBtn');
assert.ok(await page.locator('#workspace').evaluate(e => e.classList.contains('hidden')));
assert.deepEqual(errors, [], errors.join('\n'));
await browser.close(); srv.close();
console.log('E2E OK');
